name: Build and Release Executable
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read Python version from .tool-versions
        id: python_version
        run: |
          PYTHON_VERSION=$(grep 'python' .tool-versions | awk '{print $2}')
          echo "Python version specified in .tool-versions: $PYTHON_VERSION"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirement.txt
      - name: Build executable
        run: |
          pyinstaller --onefile script.py
          mv dist/script sway_start
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sway_start
          asset_name: sway_start
          asset_content_type: application/octet-stream
