name: Build and Release Executable
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read Python version from .tool-versions
        id: python_version
        run: |
          PYTHON_VERSION=$(grep 'python' .tool-versions | awk '{print $2}')
          echo "Python version specified in .tool-versions: $PYTHON_VERSION"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirement.txt
      - name: Build executable
        run: |
          pyinstaller --onefile script.py
          mv dist/script sway_start
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sway_start
